# diffusion_policy_3d/config/train_dp3.yaml

defaults:
  - _self_
  - task: my_task

logging:
  group: dp3_test_group
  name: dp3_test_run
  project: my_dp3_project

training:
  seed: 42
  debug: true
  num_epochs: 5
  gradient_accumulate_every: 1
  max_train_steps: 20
  max_val_steps: 5
  val_every: 9999       # ❌ 禁用 validation
  rollout_every: 9999   # ❌ 禁用 rollout
  sample_every: 1
  checkpoint_every: 1
  use_ema: false
  resume: false
  device: cuda
  tqdm_interval_sec: 0.5
  lr_scheduler:
    name: linear
  lr_warmup_steps: 10

checkpoint:
  save_ckpt: true
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    top_k: 1
    monitor: train_action_mse_error  # ✅ 改为不依赖 rollout 的指标
    mode: min

dataloader:
  batch_size: 1
  shuffle: false
  num_workers: 0

val_dataloader:
  batch_size: 1
  shuffle: false
  num_workers: 0

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
